apiVersion: v2
name: mathtrail-mentor
version: 0.1.0
description: MathTrail Mentor Service chart
dependencies:
  - name: mathtrail-service-lib
    version: "0.1.1"
    repository: "https://RyazanovAlexander.github.io/mathtrail-charts/charts"
