apiVersion: v2
name: mentor-api
version: 0.1.0
description: MathTrail Mentor Service chart
dependencies:
  - name: mathtrail-service-lib
    version: "0.1.1"
    repository: "https://MathTrail.github.io/charts/charts"
